export {
  CredentialError,
  MissingEnvSecretError,
  ModelRefreshError,
  ProfileValidationError,
  TargetResolutionError,
  type AuthConfig,
  type ChangePlan,
  type ConnectionPlan,
  type CredentialAuthBinding,
  type CredentialBinding,
  type CredentialErrorCode,
  type CredentialResolver,
  type CredentialStatus,
  type CredentialVault,
  type Diagnostic,
  type DiagnosticLevel,
  type GlobalConfig,
  type Extensions,
  type JsonPrimitive,
  type JsonValue,
  type LappProfile,
  type LappProvider,
  type ModelDescriptor,
  type ModelDiscoveryConfig,
  type ModelEntry,
  type ModelRef,
  type ModelSelector,
  type PartialFailureCause,
  type ModelsConfig,
  type ProfileInspection,
  type ProviderConfig,
  type ResolvedAuth,
  type ResolvedConnection,
  type SecretRef,
  type SecretScheme,
  type VaultCredentialStatus,
  type VaultEnvelopeV1,
  type VaultPutOptions,
  type ValidationResult,
} from "./types.js";

export {
  inspectProfile,
  loadProfile,
  readProfileStable,
  resolveLappRoot,
  type LoadProfileOptions,
} from "./config/discovery.js";
export { validateProfile } from "./validate/index.js";
export {
  createProfile,
  removeModel,
  removeProvider,
  setDefault,
  upsertModel,
  upsertProvider,
  prepareProviderUpdate,
  type CredentialInput,
  type CredentialWarning,
  type CreateProfileInput,
  type ManagedAuthConfig,
  type ManagedProviderInput,
  type ModelInput,
  type ModelTarget,
  type ProviderInput,
  type PendingVaultWrite,
  type PrepareProviderUpdateResult,
} from "./manage/index.js";
export { planChanges } from "./plan.js";
export {
  ProfileUpdatePartialFailureError,
  writeProfileAtomic,
  type WriteOptions,
} from "./write/atomic.js";
export {
  listModels,
  resolveConnection,
  selectConnection,
  type ListModelsOptions,
  type ResolveConnectionOptions,
  type SelectConnectionOptions,
} from "./connection.js";
export {
  LAPP_VAULT_SERVICE,
  VAULT_SECRET_PATTERN,
  assertCredentialRequestOrigin,
  createCredentialResolver,
  credentialBindingForProvider,
  credentialBindingsEqual,
  formatVaultSecretRef,
  normalizeCredentialOrigin,
  openSystemCredentialVault,
  parseSecretRef,
  parseVaultSecretRef,
  redactSecret,
  resolveAuthConfig,
  resolveSecret,
  type CredentialResolverOptions,
  type ResolveSecretOptions,
  type VaultReference,
} from "./secret/index.js";
export {
  refreshModels,
  type RefreshModelsOptions,
  type RefreshModelsResult,
} from "./sync/index.js";
export {
  createLappClient,
  StreamingUnsupportedError,
  type ChatInput,
  type ChatMessage,
  type CreateClientOptions,
  type ExecuteWithToolsOptions,
  type ExecuteWithToolsResult,
  type LappClient,
  type LappResponse,
  type LappStreamEventUnion,
  type ParsedToolCall,
  type TestConnectionResult,
  type ToolDefinition,
  type ToolHandler,
} from "./client/index.js";
export {
  createImageGenerationClient,
  createMusicGenerationClient,
  createSpeechSynthesisClient,
  createVideoGenerationClient,
  GenerationClientError,
  type ArtifactPart,
  type AudioStreamEvent,
  type CreateGenerationClientOptions,
  type DownloadArtifactOptions,
  type GenerationArtifact,
  type GenerationArtifactSource,
  type GenerationClientErrorCode,
  type GenerationClientFeatures,
  type GenerationEvent,
  type GenerationFailure,
  type GenerationFailureCode,
  type GenerationJob,
  type GenerationOperation,
  type GenerationOutput,
  type GenerationPart,
  type GenerationState,
  type GenerationTarget,
  type GenerationTerminal,
  type ImageGenerationClient,
  type ImageGenerationInput,
  type ImageSize,
  type MusicGenerationClient,
  type MusicGenerationInput,
  type SpeechSynthesisClient,
  type SpeechSynthesisInput,
  type TextPart,
  type VideoGenerationClient,
  type VideoGenerationInput,
  type WaitOptions,
} from "./media/index.js";
export {
  LAPP_MANAGER_BRIDGE_PROTOCOL_VERSION,
  type LappManagerBridgeV1,
  type ManagerAuthView,
  type ManagerCredentialView,
  type ManagerErrorCode,
  type ManagerErrorView,
  type ManagerFeature,
  type ManagerHandshake,
  type ManagerInvalidatedEvent,
  type ManagerOperation,
  type ManagerPhase,
  type ManagerProfileView,
  type ManagerProviderView,
  type ManagerResult,
  type ManagerSnapshot,
  type ManagerTestConnectionRequest,
  type ManagerTestConnectionView,
  type ManagerTransactionRequest,
  type ManagerTransactionResult,
} from "./manager/contract.js";
export {
  commitProfileTransaction,
  computeProfileRevision,
  createNodeLappManagerHost,
  ProfilePathInvalidError,
  ProfileRevisionConflictError,
  type CommitProfileTransactionOptions,
  type CommitProfileTransactionResult,
  type CreateNodeLappManagerHostOptions,
} from "./manager/host.js";
export {
  inspectWriterLock,
  LAPP_STATE_HOME_ENV,
  ProfileLockInvalidError,
  ProfileLockedError,
  repairWriterLock,
  resolveLappStateHome,
  validateWriterLockOwner,
  withWriterLock,
  writerLockPaths,
  WRITER_LOCK_OWNER_FILE,
  WRITER_LOCK_RELATIVE_PATH,
  type WriterLockInspection,
  type WriterLockOwnerValidation,
  type WriterLockOwnerValidationCode,
  type WriterLockOptions,
  type WriterLockOwner,
} from "./writer/lock.js";
export {
  ProfileReadUnstableError,
  readStable,
  type StableReadOptions,
} from "./writer/stable-read.js";
